CREATE TABLE sa_token_store (
  cache_key VARCHAR(191) NOT NULL,
  value_blob LONGBLOB NOT NULL,
  expires_at BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT SA_TOKEN_STORE_PK PRIMARY KEY (cache_key)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX SA_TOKEN_STORE_IX1 ON sa_token_store (expires_at);
